### PR TITLE
Feature/upgrade ember

### PR DESCRIPTION
**Pull request by mansona**
This is mostly just upgrading ember using ember-cli-upgrade but it's also updating `@google-cloud/storage` to version 1.6.0 because the current dependency version doesn't work with Node 10.x

I have tested this deployment and everything is working 👌

### CODE REVIEW

**Comment by mansona** [comment]
thanks for merging this @knownasilya 🎉 

Any chance of getting it released to npm? I'm happy to help if there is any way that I can 👍

**Comment by knownasilya** [comment]
I'll publish it in a second, but I can also add you to the repo and npm for the future (if you want). What's your npm username?

**Comment by knownasilya** [comment]
Published as v0.4.0

**Comment by mansona** [comment]
sure that would be useful @knownasilya 👍 

my npm username is real_ate https://www.npmjs.com/~real_ate

**Pull request merged**
